# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: kmui2/rise-ci

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run Jest Tests
          command: npm run test:coverage

      # send converage to coveralls
      - run:
          name: Upload Coverage to Coveralls
          command: cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

      - add_ssh_keys
      - run:
          name: Deploy server to droplet
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan ${DEPLOY_HOST} >> ~/.ssh/known_hosts
              npm run deploy
            fi
      - run:
          name: Publish application to Expo
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              expo login --username ${EXPO_USERNAME} --password ${EXPO_PASSWORD}
              expo publish
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
